navbar-links:
  Home page: "https://egoralmikeev.github.io"

theme: jekyll-theme-hacker
show_downloads: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

plugins:
  - jekyll-paginate
  - jekyll-sitemap
